### ISSUE TITLE
Travis CI Enterprise support planned?

### ISSUE THREAD

**Issue by gabel** [pwmckenna/node-travis-encrypt#23]
Is this planned? 

Travis cli login to travis enterprise howto: http://stackoverflow.com/questions/39513502/how-to-login-into-a-travis-enterprise-using-travis-cli

**Comment by pwmckenna** [comment]
Hi @gabel I don't use Travis much anymore, so I don't do much in the way of new features. If you'd like to make a PR it would be very much welcomed.

**Comment by gabel** [comment]
@pwmckenna thanks for the feedback 😊 I'll take that into consideration
