### ISSUE TITLE
Travis CI Pro fix needs to be backported for travis-encrypt to work

### ISSUE THREAD

**Issue by kaizhu256** [pwmckenna/node-travis-encrypt#6]
need to bump travis-ci dependency in package.json to include the following patch:

https://github.com/pwmckenna/node-travis-ci/commit/7d1eb44f3b6b92be6e04f9394ca811b84b660d41#diff-9ca2b835b96fd3a57aac1782b9df9e7c

specifically:
lib/travis-ci.js
-            name: 'Travis Pro',
+            name: 'Travis CI Pro',

**Comment by pwmckenna** [comment]
somehow let this slip. the version was set to ^2.0.0, so hopefully it picked up the 2.0.3 release, but I just bumped it as part of the 1.1.1 release. thanks!
